import type { Metadata } from 'next'
import { Open_Sans as FontSans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import { cn } from '@/lib/utils'

import './globals.css'

export const metadata: Metadata = {
  title: 'Team chat application',
  description: 'Generated by create next app',
}

const font = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            font.variable,
          )}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
